name: airflow-sandbox

on: [push, pull_request]

jobs:

  build-airflow-celery-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "build airflow celery example on bionic amd64"        
      run: |
            cd airflow/example1
            docker-compose -f docker-compose-celery.yaml up -d        

  build-airflow-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # - name: "deploy codecov checkstyle maven(single pom) on bionic arm64"        
    #   run: |
    #         cd codecov-test2 && mvn clean package
    #         mvn cobertura:cobertura
    #         bash <(curl -s https://codecov.io/bash)  

          

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!